### ISSUE TITLE
Support for Multiple NIC in Viya-ARK

### ISSUE THREAD

**Issue by wweghe** [sassoftware/viya-ark#28]
Hi, 
now that Viya 3.5 supports installing on servers with >1 NIC, are there plans to add this support in Viya-ARK ?
I just tried on a machine with > 1 NIC, and got this message from Viya-ARK : 
fatal: [deployTarget]: FAILED! => {
    "assertion": "(num_priv_ips.stdout | int) <= (max_num_priv_ips | int)",
    "changed": false,
    "evaluated_to": false,
    "msg": "\"This server seems to have 2 IP addresses.\nIt should only have 1 at most.\nThis will require more work for Consul to successfully start.\nPlease read the Deployment guide and search for the reference to the following parameter: consul_bind_adapter=\nYou can add --skip-tags skipipsfail to suppress this failure and message.\"\n"
}

Moreover, the reference to "consul_bind_adapter" should no longer be used in Viya 3.5

**Comment by erharb** [comment]
Multi-NIC support was added in Viya 3.5, though it still requires reference to the documentation to setup the necessary vars entries. Since the latest version of Viya ARK supports Viya 3.4 and 3.5 it would require first detecting which version of Viya the playbook is running on and then offer up the appropriate message conditionally

**Comment by AlissaSchleich** [comment]
Have added this to our support queue to be addressed
