### ISSUE TITLE
mmu-start-feedbackToShell

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya-ark#3]
I'd like to request a regular feedback to the shell every xx minutes so a user is confident that the playbook is still running as expected.  For example, I cannot recall when I executed my mmu-start playbook and I'd like feedback in the shell that it's still running as expected.

TASK [Start SAS all services which might take a while] *************************************************************************************************
changed: [TES_CAS_Controller]

**Comment by erharb** [comment]
That is actually not easy to do with Ansible, just as a matter of the architecture:
https://github.com/ansible/ansible/issues/3887


That said I know we all like seeing progress even if its just dots or spinny things so we don't think something is hung, so I came up with some modules that show dots on screen every so often as tasks run and report back as complete, feel free to try it out and let me know what you think of it:
https://github.com/erharb/ansible-progress

**Comment by erharb** [comment]
Just to clarify I'm not saying it's impossible, but that it would be a significant amount of effort since each task that we desire to have this regular feedback would need to be run using Ansible's async methods and then have a new looping task which may involve a custom python module, shell script, etc to check in on and report the progress of the specific task in some way (such as log parsing or service status checks).

**Comment by andybouts** [comment]
Thanks erharb, your ../ansible-progress is really clever and would be a great way to show the user some feedback while waiting.

**Comment by AlissaSchleich** [comment]
In reviewing this feature request, we have decided the effort is too great for the gain at this time.
