### ISSUE TITLE
Viya35-ark-1.1 pre-install playbook why check for free disk space on /opt?

### ISSUE THREAD

**Issue by bheinsius** [sassoftware/viya-ark#36]
viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/defaults/main.yml lists:

```
## storage ##
storage_list:
  # update as needed.
  - { path: /, min_storage_mb: 5000, min_io: 2}
  - { path: /opt/sas, min_storage_mb: 40000, min_io: 2, permission: 755}
  - { path: /var/cache, min_storage_mb: 15000, min_io: 2}
  - { path: /opt, min_storage_mb: 40000, min_io: 2, permission: 755}

```
Since Viya is installed in /opt/sas, a free disk space check for /opt/sas makes sense.
Why is /opt also checked?

**Comment by erharb** [comment]
/opt/sas could be mounted on a different volume from /opt
________________________________

**Comment by bheinsius** [comment]
That is indeed the case, my /opt/sas/ is symlinked to a larger disk.
So why check /opt?

**Comment by erwangranger** [comment]
Hello, 

in Viya-ARK, we try to walk the fine between flexibility, and simplicity. 

For each item in this list, viya-ark will:
1) check if it exists
2) create it if it does not
3) check it has enough free space. 

If /opt exists but /opt/sas does not, viya-ark tries to be helpful and take care of things, by creating /opt/sas. However, the only thing that it can do, is create it as a subfolder of /opt. 
In cases like yours, however, where you took the time to pre-create /opt/sas, it merely checks sizes, and yes, if your /opt is too small, it will give you a "false positive". 

I think that we meant the list to be: 

```yaml
## storage ##
storage_list:
  # update as needed.
  - { path: /, min_storage_mb: 5000, min_io: 2}
  - { path: /opt, min_storage_mb: 40000, min_io: 2, permission: 755}
  - { path: /opt/sas, min_storage_mb: 40000, min_io: 2, permission: 755}
  - { path: /var/cache, min_storage_mb: 15000, min_io: 2}
```

Although the /opt check seems extraneous, it would help in a case where your /opt is too small (often, it's only 10 GB and part of the root partition). In that case, instead of creating /opt/sas and then complaining it does not have enough room, it would complain that /opt does not have enough room. 

I do agree that having it as the last item in the list is probably negating this advantage. 

Would you agree it would make sense to move it up between / and /opt/sas the way I have it above in this comment? Would a comment in the YAML file, explaining that the size of /opt is actually not important, help? 

In your situation, I'd expect you to either remove that /opt line, of change required size to something that works for you.

**Comment by bheinsius** [comment]
Changing the order and extra comments would help but I think what would maybe make the most sense is:

1. check if /opt/sas exists and if so, check /opt/sas and not /opt.
2. if /opt/sas does not exist, check /opt

I don't know much about Ansible playbooks so I have no idea if this is viable or even possible.

Your explanation and suggestion to remove the /opt line or change the required size works for me for now. Thanks for your support.
