### ISSUE TITLE
Option to check online repos

### ISSUE THREAD

**Issue by j08rebelo** [sassoftware/viya-ark#38]
Dear team,

I've been using the deployment report tool, mainly over these two features:
- A listing of all SAS RPM packages installed on a host and each package's attributes
- A listing of all system services delivered by SAS and each service's attributes

The report also provides an assessment if there are any binary updates and hotfixes available. But i've noticed that if a customer uses a local mirror repository, this tool will fetch the information of that same repository. I was hoping that the tool would also gather compare and gather information from an online repository, to either there are updates available. This option would allow to check first if it was necessary to upgrade the local mirror repos (preventing from doing that blindly) and also preventing a false sense of security for the customer that everything is "up-to-date".

Is there maybe an option to allow this sort of check?

Best Regards,
Jorge Rebelo

**Comment by erharb** [comment]
Unfortunately that is not directly possible because when mirrors are use we cannot detect or access remote SAS repos you are entitled to, only what's available in the mirror. 

That said some fixes to the hotfix detection portion of the deployment report is coming up in the next release, which doesn't require knowledge of entitled SAS repos, so I think that should at least provide some indication when using mirrors that the mirror can be updated to pick something up.
