### ISSUE TITLE
using Viya-ark with crontab / monitoring uptime

### ISSUE THREAD

**Issue by devopsasadm** [sassoftware/viya-ark#54]
Hey,

Is there a way to use crontab with viya ark to restart services if they are not up?  like if the server is taken down and then brought back up like you could with sas.servers in SAS 9.4?

**Comment by kevinlinglesas** [comment]
crontab can be used to execute anything.  ansible-playbooks included.  crontab doesn't help with the quesiton of "if they are not up" though.   cron will simply fire off at configured times/intervals.  Not familiar with sas.servers in 9.4 personally, so can't formulate a comparison.    not really clear on what problem you are trying to solve.

**Comment by erharb** [comment]
Perhaps this is not so much about interval based starts but rather starting services automatically after a server goes down when it comes back up? 

While that could work fine in a single machine environment, the problem becomes when you spread services out to multiple hosts and dependencies of services between hosts don't always gracefully handle that. That is the reason why we actually recommend disabling having services start automatically when services are coming up. This is done using the systemctl (or service command), for example: `systemctl disable sas-viya-all-services`

The mmsu scripts were intended to handle gracefully starting and stopping services across multiple hosts because having services automatically start on individual server startup didn't work very well in most cases.

**Comment by devopsasadm** [comment]
Administrators (outside of the system) routinely bring servers down and automation would be helpful or in a cloud environment as part of cost savings.  It is managed today using viya-ark but it is manual intervention. The sas-viya-all-services is disabled.  Could be put in the boot probably but not sure without being able to test that certain services were up for it to do a re-try if you have multiple servers.

**Comment by erwangranger** [comment]
I have done something slightly similar in the past. 

What you can do is add a step at the beginning of the start playbook that makes sure everything is reachable, and only proceeds when it it. 

It looks like:

```yaml
- hosts: sas_all
  gather_facts: no
  tasks:
    - name: Wait for all machines to be reachable (up to 1800 seconds, aka 30 minutes)
      any_errors_fatal: true
      wait_for_connection:
        timeout: 1800
      tags:
        - always
```

So, assuming that you configure the Ansible Controller to execute this playbook when it boots, and assuming that you reboot all the servers more or less at same time, including the Ansible Controller, you'd get close to the desired behavior. 
If your Ansible Controller is one of your Viya machines, that'd be pretty much the case. 

I hope this helps and gives you some ideas.

**Comment by devopsasadm** [comment]
I'm going to play around with this.  Thanks for the idea.
