### ISSUE TITLE
Why the 5 GB size enforcement on root disk

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/viya-ark#83]
Currently Viya ARK asserts that the root disk has 5 GB of disk space available:

https://github.com/sassoftware/viya-ark/blob/7b851591660dca29329e748fda72374b8a0a79e2/playbooks/pre-install-playbook/roles/viya-ark.preinstall/defaults/main.yml#L37

I don't see such a requirement anywhere in the documentation though. The reason for asking is that in Azure, the RHEL images after 7.7 are LVM partioned, with the result being that there are more, smaller partitions, rather than one large one on "/":

```
sda                 8:0    0   64G  0 disk
├─sda1              8:1    0  500M  0 part /boot
├─sda2              8:2    0   63G  0 part
│ ├─rootvg-tmplv  253:0    0    2G  0 lvm  /tmp
│ ├─rootvg-usrlv  253:1    0   10G  0 lvm  /usr
│ ├─rootvg-homelv 253:2    0    1G  0 lvm  /home
│ ├─rootvg-varlv  253:3    0   20G  0 lvm  /var
│ └─rootvg-rootlv 253:4    0    2G  0 lvm  /
├─sda14             8:14   0    4M  0 part
└─sda15             8:15   0  495M  0 part /boot/efi
```

In this case / only has 2 GB, so the Viya ARK check fails. I ran a basic VA deployment on this image without enlarging the 2 GB root disk and the deployment completed successfully though, so it's not clear where the requirement came from.

**Comment by erharb** [comment]
It is configurable to tune for your needs, however it was a general safeguard since we cannot assume to know every possible directory where files may be installed are handled by separate volumes. If you cannot increase your root volume size just in case it's actually needed, then you can modify the yml file to reduce the threshhold for your purposes.
