### ISSUE TITLE
"sas-viya-sasdatasvrc-postgres-node0" service inactive (dead) when starting Viya 3.5 with Viya-Ark

### ISSUE THREAD

**Issue by irchum** [sassoftware/viya-ark#86]
**Describe the bug**
A customer has opened a track (7613486167) as he found that "sas-viya-sasdatasvrc-postgres-node0" service is not started although Viya is operational. He uses Viya-Ark to start and stop Viya 3.5 (MPP deployment). "sas-viya-all-services" shows "sas-viya-sasdatasvrc-postgres-node0" is up. However, "systemctl status sas-viya-sasdatasvrc-postgres-node0" shows:
● sas-viya-sasdatasvrc-postgres-node0.service - LSB: start and stop postgresql service for postgres cluster
   Loaded: loaded (/etc/rc.d/init.d/sas-viya-sasdatasvrc-postgres-node0; bad; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

**Environment**
- [ ] Ansible version: 2.9.9
- [ ] Python version: 2.7.5
- [ ] OS version: RHEL 7
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed? 3.5

**To Reproduce**
1. I have tested in my environment. I have the same behavior after stoping and restarting Viya using viya-mmsu playbooks. 

**Expected behavior**
sas-viya-sasdatasvrc-postgres-node0 should have been started when starting Viya with viya-mmsu. Why sas-viya-sasdatasvrc-postgres-node0 is not started? 
[sas-viya-all-services.txt](https://github.com/sassoftware/viya-ark/files/7793515/sas-viya-all-services.txt)
[pgpool0_statusall.txt](https://github.com/sassoftware/viya-ark/files/7793516/pgpool0_statusall.txt)

**Comment by cuddlehub** [comment]
Since Viya Ark tool uses the cluster level shell script to start the cluster not OS services, systemctl status may not report correctly.

https://go.documentation.sas.com/doc/en/calcdc/3.5/calsrvinf/n00000sasinfrdatasrv000admin.htm#n03001sasinfrdatasrv000admin

IMPORTANT The systemctl command does not provide a status of a service that it did not start. If the systemctl command has to respond to a status command of a service that was started by another process, then you must first run the start command of that service to bind it to the process and then run the status command.

**Comment by cuddlehub** [comment]
Re-open the issue. We plan to add the information to the Viya Ark Readme to denote it.

**Comment by kevinlinglesas** [comment]
This issue resolved by release [Viya35-ark-1.15](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.15)
